// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

package hep.lcio.event;


/** The LCIO TrackState class.
 * 
 * @author gaede, engels
 * @version $Id:$
 */

public interface TrackState extends LCObject {

     /** The location of the track state.
     *   Location can be set to: TrackState::AtIP, TrackState::AtFirstHit, TrackState::AtLastHit, TrackState::AtCalorimeter, TrackState::AtVertex, TrackState::AtOther
     */
    public int getLocation();

    /** Impact paramter of the track
     *  in (r-phi).
     */
    public float getD0();

    /** Phi of the track at the reference point.
     * @see getReferencePoint
     */
    public float getPhi();

    /** Omega is the signed curvature of the track in [1/mm].
     * The sign is that of the particle's charge.
     */
    public float getOmega();

    /** Impact paramter of the track
     *  in (r-z).
     */
    public float getZ0();

    /** Lambda is the dip angle of the track in r-z at the reference point. 
     * @see getReferencePoint
     */
    public float getTanLambda();
    /**  Blocal is the b-field at the reference point
     *
     */
    public float getBLocal();
    
    /** Covariance matrix of the track parameters. Stored as lower triangle matrix where
     * the order of parameters is:   d0, phi, omega, z0, tan(lambda).
     * So we have cov(d0,d0), cov( phi, d0 ), cov( phi, phi), ...
     */
    public float[] getCovMatrix();

    /** Reference point of the track parameters, e.g. the origin at the IP, or the position
     *  of the first/last hits or the entry point into the calorimeter.
     */
    public float[] getReferencePoint();
  /** 3-momentum at the perigee or the reference point
   *
     */
    public float[] getMomentum(); 
    // any location other than the ones defined below  
    public final static int AtOther = 0;  // Any location other than the ones defined below. 
    
    public final static int AtPerigee = 1;  //track state at perigee, which is what the track finder returns
    public final static int AtIP = 2;  // this is at the target
    public final static int AtTarget = 2;  // this is at the target
    public final static int AtFirstHit = 3;
    public final static int AtLastHit = 4;
    public final static int AtCalorimeter = 5;
    public final static int AtVertex = 6;
    public final static int LastLocation = AtVertex;
} // class or interface

